name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "legenda/legenda.md"
        source: "tests/a.txt,tests/b.txt"
        source: "podziekowania/podziekowania.md"
        source: "topka/150.md,topka/250.md,topka/500.md,topka/1000.md,topka/10000.md,topka/100000.md,topka/nieobslugiwane-boty.md"
        source: "index.md"
        source: "retype.yml"
        target: /opt/_data/topbots.pl
